// Code generated by delegationtest - DO NOT EDIT.

package delegationtest

import "github.com/ipfs/go-cid"

var (
	TokenAliceBobCID = cid.MustParse("bafyreicidrwvmac5lvjypucgityrtjsknojraio7ujjli4r5eyby66wjzm")
	TokenAliceBob    = mustGetDelegation(TokenAliceBobCID)
)

var (
	TokenBobCarolCID = cid.MustParse("bafyreihxv2uhq43oxllzs2xfvxst7wtvvvl7pohb2chcz6hjvfv2ntea5u")
	TokenBobCarol    = mustGetDelegation(TokenBobCarolCID)
)

var (
	TokenCarolDanCID = cid.MustParse("bafyreihclsgiroazq3heqdswvj2cafwqbpboicq7immo65scl7ahktpsdq")
	TokenCarolDan    = mustGetDelegation(TokenCarolDanCID)
)

var (
	TokenDanErinCID = cid.MustParse("bafyreicja6ihewy64p3ake56xukotafjlkh4uqep2qhj52en46zzfwby3e")
	TokenDanErin    = mustGetDelegation(TokenDanErinCID)
)

var (
	TokenErinFrankCID = cid.MustParse("bafyreicjlx3lobxm6hl5s4htd4ydwkkqeiou6rft4rnvulfdyoew565vka")
	TokenErinFrank    = mustGetDelegation(TokenErinFrankCID)
)

var (
	TokenCarolDan_InvalidExpandedCommandCID = cid.MustParse("bafyreid3m3pk53gqgp5rlzqhvpedbwsqbidqlp4yz64vknwbzj7bxrmsr4")
	TokenCarolDan_InvalidExpandedCommand    = mustGetDelegation(TokenCarolDan_InvalidExpandedCommandCID)
)

var (
	TokenDanErin_InvalidExpandedCommandCID = cid.MustParse("bafyreifn4sy5onwajx3kqvot5mib6m6xarzrqjozqbzgmzpmc5ox3g2uzm")
	TokenDanErin_InvalidExpandedCommand    = mustGetDelegation(TokenDanErin_InvalidExpandedCommandCID)
)

var (
	TokenErinFrank_InvalidExpandedCommandCID = cid.MustParse("bafyreidmpgd36jznmq42bs34o4qi3fcbrsh4idkg6ejahudejzwb76fwxe")
	TokenErinFrank_InvalidExpandedCommand    = mustGetDelegation(TokenErinFrank_InvalidExpandedCommandCID)
)

var (
	TokenCarolDan_ValidAttenuatedCommandCID = cid.MustParse("bafyreiekhtm237vyapk3c6voeb5lnz54crebqdqi3x4wn4u4cbrrhzsqfe")
	TokenCarolDan_ValidAttenuatedCommand    = mustGetDelegation(TokenCarolDan_ValidAttenuatedCommandCID)
)

var (
	TokenDanErin_ValidAttenuatedCommandCID = cid.MustParse("bafyreicrvzqferyy7rgo75l5rn6r2nl7zyeexxjmu3dm4ff7rn2coblj4y")
	TokenDanErin_ValidAttenuatedCommand    = mustGetDelegation(TokenDanErin_ValidAttenuatedCommandCID)
)

var (
	TokenErinFrank_ValidAttenuatedCommandCID = cid.MustParse("bafyreie6fhspk53kplcc2phla3e7z7fzldlbmmpuwk6nbow5q6s2zjmw2q")
	TokenErinFrank_ValidAttenuatedCommand    = mustGetDelegation(TokenErinFrank_ValidAttenuatedCommandCID)
)

var (
	TokenCarolDan_InvalidSubjectCID = cid.MustParse("bafyreifgksz6756if42tnc6rqsnbaa2u3fdrveo7ek44lnj2d64d5sw26u")
	TokenCarolDan_InvalidSubject    = mustGetDelegation(TokenCarolDan_InvalidSubjectCID)
)

var (
	TokenDanErin_InvalidSubjectCID = cid.MustParse("bafyreibdwew5nypsxrm4fq73wu6hw3lgwwiolj3bi33xdrbgcf3ogm6fty")
	TokenDanErin_InvalidSubject    = mustGetDelegation(TokenDanErin_InvalidSubjectCID)
)

var (
	TokenErinFrank_InvalidSubjectCID = cid.MustParse("bafyreicr364mj3n7x4iyhcksxypelktcqkkw3ptg7ggxtqegw3p3mr6zc4")
	TokenErinFrank_InvalidSubject    = mustGetDelegation(TokenErinFrank_InvalidSubjectCID)
)

var (
	TokenCarolDan_InvalidExpiredCID = cid.MustParse("bafyreieokte3abvnnj77uhhlwbem4fukvaujpp4jtirqof2r6zrdwv6may")
	TokenCarolDan_InvalidExpired    = mustGetDelegation(TokenCarolDan_InvalidExpiredCID)
)

var (
	TokenDanErin_InvalidExpiredCID = cid.MustParse("bafyreia76qfn2krqnzzgzoyvttei5fc74ybyidqb6omoa26jn6u2wy4kmi")
	TokenDanErin_InvalidExpired    = mustGetDelegation(TokenDanErin_InvalidExpiredCID)
)

var (
	TokenErinFrank_InvalidExpiredCID = cid.MustParse("bafyreiaglb3rgguhlsjpkpuowr3zfwjrp2c6o2pl3llib3kj2pzusaecda")
	TokenErinFrank_InvalidExpired    = mustGetDelegation(TokenErinFrank_InvalidExpiredCID)
)

var (
	TokenCarolDan_InvalidInactiveCID = cid.MustParse("bafyreicea5y2nvlitvxijkupeavtg23i7ktjk3uejnaquguurzptiabk4u")
	TokenCarolDan_InvalidInactive    = mustGetDelegation(TokenCarolDan_InvalidInactiveCID)
)

var (
	TokenDanErin_InvalidInactiveCID = cid.MustParse("bafyreifsgqzkmxj2vexuts3z766mwcjreiisjg2jykyzf7tbj5sclutpvq")
	TokenDanErin_InvalidInactive    = mustGetDelegation(TokenDanErin_InvalidInactiveCID)
)

var (
	TokenErinFrank_InvalidInactiveCID = cid.MustParse("bafyreifbfegon24c6dndiqyktahzs65vhyasrygbw7nhsvojn6distsdre")
	TokenErinFrank_InvalidInactive    = mustGetDelegation(TokenErinFrank_InvalidInactiveCID)
)

var (
	TokenCarolDan_ValidExamplePolicyCID = cid.MustParse("bafyreibtfrp2njnkjrcuhxd4ebaecmpcql5knek2h2j2fjzu2sij2tv6ei")
	TokenCarolDan_ValidExamplePolicy    = mustGetDelegation(TokenCarolDan_ValidExamplePolicyCID)
)

var (
	TokenDanErin_ValidExamplePolicyCID = cid.MustParse("bafyreidxfwbkzujpu7ivulkc7b6ff4cpbzrkeklmxqvyhhmkmym5b45e2e")
	TokenDanErin_ValidExamplePolicy    = mustGetDelegation(TokenDanErin_ValidExamplePolicyCID)
)

var (
	TokenErinFrank_ValidExamplePolicyCID = cid.MustParse("bafyreiatkvtvgakqcrdk6vgrv7tbq5rbeiqct52ep4plcftp2agffjyvp4")
	TokenErinFrank_ValidExamplePolicy    = mustGetDelegation(TokenErinFrank_ValidExamplePolicyCID)
)

var ProofAliceBob = []cid.Cid{
	TokenAliceBobCID,
}

var ProofAliceBobCarol = []cid.Cid{
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan = []cid.Cid{
	TokenCarolDanCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin = []cid.Cid{
	TokenDanErinCID,
	TokenCarolDanCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank = []cid.Cid{
	TokenErinFrankCID,
	TokenDanErinCID,
	TokenCarolDanCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidExpandedCommand = []cid.Cid{
	TokenCarolDan_InvalidExpandedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidExpandedCommand = []cid.Cid{
	TokenDanErin_InvalidExpandedCommandCID,
	TokenCarolDan_InvalidExpandedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidExpandedCommand = []cid.Cid{
	TokenErinFrank_InvalidExpandedCommandCID,
	TokenDanErin_InvalidExpandedCommandCID,
	TokenCarolDan_InvalidExpandedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_ValidAttenuatedCommand = []cid.Cid{
	TokenCarolDan_ValidAttenuatedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_ValidAttenuatedCommand = []cid.Cid{
	TokenDanErin_ValidAttenuatedCommandCID,
	TokenCarolDan_ValidAttenuatedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_ValidAttenuatedCommand = []cid.Cid{
	TokenErinFrank_ValidAttenuatedCommandCID,
	TokenDanErin_ValidAttenuatedCommandCID,
	TokenCarolDan_ValidAttenuatedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidSubject = []cid.Cid{
	TokenCarolDan_InvalidSubjectCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidSubject = []cid.Cid{
	TokenDanErin_InvalidSubjectCID,
	TokenCarolDan_InvalidSubjectCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidSubject = []cid.Cid{
	TokenErinFrank_InvalidSubjectCID,
	TokenDanErin_InvalidSubjectCID,
	TokenCarolDan_InvalidSubjectCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidExpired = []cid.Cid{
	TokenCarolDan_InvalidExpiredCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidExpired = []cid.Cid{
	TokenDanErin_InvalidExpiredCID,
	TokenCarolDan_InvalidExpiredCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidExpired = []cid.Cid{
	TokenErinFrank_InvalidExpiredCID,
	TokenDanErin_InvalidExpiredCID,
	TokenCarolDan_InvalidExpiredCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidInactive = []cid.Cid{
	TokenCarolDan_InvalidInactiveCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidInactive = []cid.Cid{
	TokenDanErin_InvalidInactiveCID,
	TokenCarolDan_InvalidInactiveCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidInactive = []cid.Cid{
	TokenErinFrank_InvalidInactiveCID,
	TokenDanErin_InvalidInactiveCID,
	TokenCarolDan_InvalidInactiveCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_ValidExamplePolicy = []cid.Cid{
	TokenCarolDan_ValidExamplePolicyCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_ValidExamplePolicy = []cid.Cid{
	TokenDanErin_ValidExamplePolicyCID,
	TokenCarolDan_ValidExamplePolicyCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_ValidExamplePolicy = []cid.Cid{
	TokenErinFrank_ValidExamplePolicyCID,
	TokenDanErin_ValidExamplePolicyCID,
	TokenCarolDan_ValidExamplePolicyCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}
