// Code generated by delegationtest - DO NOT EDIT.

package delegationtest

import gocid "github.com/ipfs/go-cid"

var (
	TokenAliceBobCID = gocid.MustParse("bafyreicidrwvmac5lvjypucgityrtjsknojraio7ujjli4r5eyby66wjzm")
	TokenAliceBob    = mustGetDelegation(TokenAliceBobCID)
)

var (
	TokenBobCarolCID = gocid.MustParse("bafyreihxv2uhq43oxllzs2xfvxst7wtvvvl7pohb2chcz6hjvfv2ntea5u")
	TokenBobCarol    = mustGetDelegation(TokenBobCarolCID)
)

var (
	TokenCarolDanCID = gocid.MustParse("bafyreihclsgiroazq3heqdswvj2cafwqbpboicq7immo65scl7ahktpsdq")
	TokenCarolDan    = mustGetDelegation(TokenCarolDanCID)
)

var (
	TokenDanErinCID = gocid.MustParse("bafyreicja6ihewy64p3ake56xukotafjlkh4uqep2qhj52en46zzfwby3e")
	TokenDanErin    = mustGetDelegation(TokenDanErinCID)
)

var (
	TokenErinFrankCID = gocid.MustParse("bafyreicjlx3lobxm6hl5s4htd4ydwkkqeiou6rft4rnvulfdyoew565vka")
	TokenErinFrank    = mustGetDelegation(TokenErinFrankCID)
)

var (
	TokenCarolDan_InvalidExpandedCommandCID = gocid.MustParse("bafyreid3m3pk53gqgp5rlzqhvpedbwsqbidqlp4yz64vknwbzj7bxrmsr4")
	TokenCarolDan_InvalidExpandedCommand    = mustGetDelegation(TokenCarolDan_InvalidExpandedCommandCID)
)

var (
	TokenDanErin_InvalidExpandedCommandCID = gocid.MustParse("bafyreifn4sy5onwajx3kqvot5mib6m6xarzrqjozqbzgmzpmc5ox3g2uzm")
	TokenDanErin_InvalidExpandedCommand    = mustGetDelegation(TokenDanErin_InvalidExpandedCommandCID)
)

var (
	TokenErinFrank_InvalidExpandedCommandCID = gocid.MustParse("bafyreidmpgd36jznmq42bs34o4qi3fcbrsh4idkg6ejahudejzwb76fwxe")
	TokenErinFrank_InvalidExpandedCommand    = mustGetDelegation(TokenErinFrank_InvalidExpandedCommandCID)
)

var (
	TokenCarolDan_ValidAttenuatedCommandCID = gocid.MustParse("bafyreiekhtm237vyapk3c6voeb5lnz54crebqdqi3x4wn4u4cbrrhzsqfe")
	TokenCarolDan_ValidAttenuatedCommand    = mustGetDelegation(TokenCarolDan_ValidAttenuatedCommandCID)
)

var (
	TokenDanErin_ValidAttenuatedCommandCID = gocid.MustParse("bafyreicrvzqferyy7rgo75l5rn6r2nl7zyeexxjmu3dm4ff7rn2coblj4y")
	TokenDanErin_ValidAttenuatedCommand    = mustGetDelegation(TokenDanErin_ValidAttenuatedCommandCID)
)

var (
	TokenErinFrank_ValidAttenuatedCommandCID = gocid.MustParse("bafyreie6fhspk53kplcc2phla3e7z7fzldlbmmpuwk6nbow5q6s2zjmw2q")
	TokenErinFrank_ValidAttenuatedCommand    = mustGetDelegation(TokenErinFrank_ValidAttenuatedCommandCID)
)

var (
	TokenCarolDan_InvalidSubjectCID = gocid.MustParse("bafyreifgksz6756if42tnc6rqsnbaa2u3fdrveo7ek44lnj2d64d5sw26u")
	TokenCarolDan_InvalidSubject    = mustGetDelegation(TokenCarolDan_InvalidSubjectCID)
)

var (
	TokenDanErin_InvalidSubjectCID = gocid.MustParse("bafyreibdwew5nypsxrm4fq73wu6hw3lgwwiolj3bi33xdrbgcf3ogm6fty")
	TokenDanErin_InvalidSubject    = mustGetDelegation(TokenDanErin_InvalidSubjectCID)
)

var (
	TokenErinFrank_InvalidSubjectCID = gocid.MustParse("bafyreicr364mj3n7x4iyhcksxypelktcqkkw3ptg7ggxtqegw3p3mr6zc4")
	TokenErinFrank_InvalidSubject    = mustGetDelegation(TokenErinFrank_InvalidSubjectCID)
)

var (
	TokenCarolDan_InvalidExpiredCID = gocid.MustParse("bafyreifrbm6bgyqdzhhcubbb7dnhq3aq6udvdbfs7mhqjs3d2ihraelufu")
	TokenCarolDan_InvalidExpired    = mustGetDelegation(TokenCarolDan_InvalidExpiredCID)
)

var (
	TokenDanErin_InvalidExpiredCID = gocid.MustParse("bafyreibbh5ujs6udphkl3exffohxsg5mdknoqzjb3gdhmuncg3qnomzemy")
	TokenDanErin_InvalidExpired    = mustGetDelegation(TokenDanErin_InvalidExpiredCID)
)

var (
	TokenErinFrank_InvalidExpiredCID = gocid.MustParse("bafyreiggzczmqlybhxljmlfot5t7o4w6fhdv7fme77a466ku73dhxtqzdq")
	TokenErinFrank_InvalidExpired    = mustGetDelegation(TokenErinFrank_InvalidExpiredCID)
)

var (
	TokenCarolDan_InvalidInactiveCID = gocid.MustParse("bafyreicea5y2nvlitvxijkupeavtg23i7ktjk3uejnaquguurzptiabk4u")
	TokenCarolDan_InvalidInactive    = mustGetDelegation(TokenCarolDan_InvalidInactiveCID)
)

var (
	TokenDanErin_InvalidInactiveCID = gocid.MustParse("bafyreifsgqzkmxj2vexuts3z766mwcjreiisjg2jykyzf7tbj5sclutpvq")
	TokenDanErin_InvalidInactive    = mustGetDelegation(TokenDanErin_InvalidInactiveCID)
)

var (
	TokenErinFrank_InvalidInactiveCID = gocid.MustParse("bafyreifbfegon24c6dndiqyktahzs65vhyasrygbw7nhsvojn6distsdre")
	TokenErinFrank_InvalidInactive    = mustGetDelegation(TokenErinFrank_InvalidInactiveCID)
)

var (
	TokenCarolDan_ValidExamplePolicyCID = gocid.MustParse("bafyreibtfrp2njnkjrcuhxd4ebaecmpcql5knek2h2j2fjzu2sij2tv6ei")
	TokenCarolDan_ValidExamplePolicy    = mustGetDelegation(TokenCarolDan_ValidExamplePolicyCID)
)

var (
	TokenDanErin_ValidExamplePolicyCID = gocid.MustParse("bafyreidxfwbkzujpu7ivulkc7b6ff4cpbzrkeklmxqvyhhmkmym5b45e2e")
	TokenDanErin_ValidExamplePolicy    = mustGetDelegation(TokenDanErin_ValidExamplePolicyCID)
)

var (
	TokenErinFrank_ValidExamplePolicyCID = gocid.MustParse("bafyreiatkvtvgakqcrdk6vgrv7tbq5rbeiqct52ep4plcftp2agffjyvp4")
	TokenErinFrank_ValidExamplePolicy    = mustGetDelegation(TokenErinFrank_ValidExamplePolicyCID)
)

var ProofAliceBob = []gocid.Cid{
	TokenAliceBobCID,
}

var ProofAliceBobCarol = []gocid.Cid{
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan = []gocid.Cid{
	TokenCarolDanCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin = []gocid.Cid{
	TokenDanErinCID,
	TokenCarolDanCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank = []gocid.Cid{
	TokenErinFrankCID,
	TokenDanErinCID,
	TokenCarolDanCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidExpandedCommand = []gocid.Cid{
	TokenCarolDan_InvalidExpandedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidExpandedCommand = []gocid.Cid{
	TokenDanErin_InvalidExpandedCommandCID,
	TokenCarolDan_InvalidExpandedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidExpandedCommand = []gocid.Cid{
	TokenErinFrank_InvalidExpandedCommandCID,
	TokenDanErin_InvalidExpandedCommandCID,
	TokenCarolDan_InvalidExpandedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_ValidAttenuatedCommand = []gocid.Cid{
	TokenCarolDan_ValidAttenuatedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_ValidAttenuatedCommand = []gocid.Cid{
	TokenDanErin_ValidAttenuatedCommandCID,
	TokenCarolDan_ValidAttenuatedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_ValidAttenuatedCommand = []gocid.Cid{
	TokenErinFrank_ValidAttenuatedCommandCID,
	TokenDanErin_ValidAttenuatedCommandCID,
	TokenCarolDan_ValidAttenuatedCommandCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidSubject = []gocid.Cid{
	TokenCarolDan_InvalidSubjectCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidSubject = []gocid.Cid{
	TokenDanErin_InvalidSubjectCID,
	TokenCarolDan_InvalidSubjectCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidSubject = []gocid.Cid{
	TokenErinFrank_InvalidSubjectCID,
	TokenDanErin_InvalidSubjectCID,
	TokenCarolDan_InvalidSubjectCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidExpired = []gocid.Cid{
	TokenCarolDan_InvalidExpiredCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidExpired = []gocid.Cid{
	TokenDanErin_InvalidExpiredCID,
	TokenCarolDan_InvalidExpiredCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidExpired = []gocid.Cid{
	TokenErinFrank_InvalidExpiredCID,
	TokenDanErin_InvalidExpiredCID,
	TokenCarolDan_InvalidExpiredCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_InvalidInactive = []gocid.Cid{
	TokenCarolDan_InvalidInactiveCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_InvalidInactive = []gocid.Cid{
	TokenDanErin_InvalidInactiveCID,
	TokenCarolDan_InvalidInactiveCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_InvalidInactive = []gocid.Cid{
	TokenErinFrank_InvalidInactiveCID,
	TokenDanErin_InvalidInactiveCID,
	TokenCarolDan_InvalidInactiveCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDan_ValidExamplePolicy = []gocid.Cid{
	TokenCarolDan_ValidExamplePolicyCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErin_ValidExamplePolicy = []gocid.Cid{
	TokenDanErin_ValidExamplePolicyCID,
	TokenCarolDan_ValidExamplePolicyCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}

var ProofAliceBobCarolDanErinFrank_ValidExamplePolicy = []gocid.Cid{
	TokenErinFrank_ValidExamplePolicyCID,
	TokenDanErin_ValidExamplePolicyCID,
	TokenCarolDan_ValidExamplePolicyCID,
	TokenBobCarolCID,
	TokenAliceBobCID,
}
