package delegation

// Code generated by github.com/selesy/go-options.  DO NOT EDIT.

import (
	"github.com/ipld/go-ipld-prime/datamodel"
	"time"
)

type Option func(c *config) error

func newConfig(options ...Option) (config, error) {
	var c config
	err := applyConfigOptions(&c, options...)
	return c, err
}

func applyConfigOptions(c *config, options ...Option) error {
	for _, o := range options {
		if err := o(c); err != nil {
			return err
		}
	}
	return nil
}

func WithExpiration(o *time.Time) Option {
	return func(c *config) error {
		c.Expiration = o
		return nil
	}
}

func WithMeta(o map[string]datamodel.Node) Option {
	return func(c *config) error {
		c.Meta = o
		return nil
	}
}

func WithNotBefore(o *time.Time) Option {
	return func(c *config) error {
		c.NotBefore = o
		return nil
	}
}
