// Code generated by internal/cmd/token DO NOT EDIT.

package token

import "github.com/ipld/go-ipld-prime/datamodel"

type Map struct {
	Keys   []string
	Values map[string]datamodel.Node
}
type List []datamodel.Node
type Map__String__Any struct {
	Keys   []string
	Values map[string]datamodel.Node
}
type List__CID []string
type Token struct {
	Issuer     string
	Audience   *string
	Subject    *string
	Command    string
	Policy     *datamodel.Node
	Args       *Map__String__Any
	Prf        *List__CID
	Nonce      *[]uint8
	Meta       *Map__String__Any
	NotBefore  *int
	Expiration *int
	IssuedAt   *int
	Cause      *string
}
